services:
  mysql:
    image: mysql:8.1
    container_name: mysql-container
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 33306:3306
    volumes:
      - data:/var/lib/mysql

volumes:
  data: